# Test against this version of Node.js
environment:
  nodejs_version: "6"
  NSIS_ROOT: C:\nsis
  my_secret:
    secure: 7aw9GKJaHNvIlfNfyv2byA==

init:
  - "SET PATH=%NSIS_ROOT%;%PATH%"

# Install scripts. (runs after repo cloning)
install:
  - cinst nsis -y -installArgs /D=%NSIS_ROOT%
  - ps: $packageVersion = (Get-Content -Raw -Path app/package.json | ConvertFrom-Json).version
  - ps: $build = $env:APPVEYOR_BUILD_NUMBER
  - ps: Update-AppveyorBuild -Version "$packageVersion-$build"
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version x64
  - npm -g install npm@next
  # install modules
  - npm install
  - npm run release
  - ps: Set-AppveyorBuildVariable -Name "deploy_version" -Value (Get-Content -Raw -Path app/package.json | ConvertFrom-Json).version

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  # - npm test

artifacts:
  - path: releases/EBA2-Admin-*-x86.exe
    name: Setup-latest-x86
  - path: releases/EBA2-Admin-*-x64.exe
    name: Setup-latest-x64

# Don't actually build.
build: off

deploy:
- provider: BinTray
  username: frieck
  api_key:
    secure: FJjduc0FvXY9kR7j2IGEL1Mm1MBBEgUiMZXg+3c5cVFuePEkCp/Rt0X0q1+CLyRX
  subject: frieck
  repo: setups
  package: ea2bp
  publish: true
  override: true
  explode: false
  artifact: Setup-latest-x86,Setup-latest-x64
  version: $(deploy_version)